# OptionPlay - Backtesting Module
# ================================
# Re-exports from subpackages for backwards compatibility

from .core import (
    BacktestConfig,
    BacktestEngine,
    BacktestResult,
    ExitReason,
    PerformanceMetrics,
    PriceSimulator,
    SimulatedTrade,
    TradeOutcome,
    TradeResult,
    TradeSimulator,
    calculate_equity_stats,
    calculate_kelly_criterion,
    calculate_max_drawdown,
    calculate_metrics,
    calculate_profit_factor,
    calculate_risk_of_ruin,
    calculate_sharpe_ratio,
    calculate_sortino_ratio,
    calculate_streaks,
)
from .simulation import (
    OptionsSimulator,
    OptionsSimulatorConfig,
    SpreadEntry,
    SpreadSnapshot,
)

# Alias for backwards compatibility
SimulatorConfig = OptionsSimulatorConfig

from .data_collector import (
    CollectionConfig,
    CollectionResult,
    DataCollector,
    create_collector,
    format_collection_status,
    run_daily_collection,
)
from .models import (  # Trained Model Support; Regime Model; Ensemble Selector
    CLUSTER_STRATEGY_MAP,
    DEFAULT_COMPONENT_WEIGHTS,
    DEFAULT_REGIME_PREFERENCES,
    FEATURE_IMPACT,
    FIXED_REGIMES,
    MIN_SCORE_THRESHOLDS,
    REGIME_NAME_MAPPING,
    SECTOR_STRATEGY_MAP,
    STRATEGIES,
    EnsembleRecommendation,
    EnsembleSelector,
    MetaLearner,
    RegimeBoundaryMethod,
    RegimeConfig,
    RegimeModel,
    RegimeState,
    RegimeStatus,
    RegimeTransition,
    RegimeType,
    RotationState,
    RotationTrigger,
    SelectionMethod,
    StrategyRotationEngine,
    StrategyScore,
    SymbolPerformance,
    TradeDecision,
    TradingParameters,
    TrainedModelLoader,
    TrainedRegimeConfig,
    TrainedStrategyConfig,
    create_percentile_regimes,
    create_strategy_score,
    format_ensemble_summary,
    format_regime_status,
    format_regime_summary,
    get_regime_for_vix,
    get_regime_recommendation,
    get_trained_model_loader,
    load_regimes,
    load_trained_regimes,
    save_regimes,
)
from .simulation import (  # NumPy batch functions; Real Options Backtester; Phase 6: Component Score Training
    EXIT_CODE_NAMES,
    OUTCOME_DB_PATH,
    BacktestTradeRecord,
    OptionQuote,
    OptionsDatabase,
    OutcomeCalculator,
    RealOptionsBacktester,
    RealSpreadEntry,
    SetupFeatures,
    SpreadFinder,
    SpreadOutcome,
    SpreadOutcomeResult,
    analyze_winning_patterns,
    batch_calculate_pnl,
    batch_calculate_spread_values,
    batch_check_exit_signals,
    calculate_symbol_stability,
    create_outcome_database,
    get_blacklisted_symbols,
    get_outcome_statistics,
    get_recommended_symbols,
    get_symbol_stability_score,
    get_trades_without_scores,
    load_outcomes_dataframe,
    load_outcomes_for_training,
    load_outcomes_with_scores,
    quick_backtest,
    quick_spread_pnl,
    run_symbol_backtest,
    save_outcomes_to_db,
    train_component_weights_from_outcomes,
    train_outcome_predictor,
    update_trade_scores,
)
from .tracking import (
    OptionBar,
    PriceBar,
    SymbolPriceData,
    TrackedTrade,
)
from .tracking import (
    TradeOutcome as TrackerOutcome,  # Alias to avoid conflict with engine.TradeOutcome
)
from .tracking import (
    TradeStats,
    TradeStatus,
    TradeTracker,
    VixDataPoint,
    create_tracker,
    format_trade_stats,
)
from .training import (
    ALL_COMPONENTS,
    DEFAULT_WEIGHTS,
    STRATEGY_COMPONENTS,
    ComponentStats,
    EpochResult,
    FeatureExtractor,
    FullRegimeTrainingResult,
    MLWeightOptimizer,
    OptimizationMethod,
    OptimizationResult,
    RegimeEpochResult,
    RegimeTrainer,
    RegimeTrainingConfig,
    RegimeTrainingResult,
    StrategyPerformance,
    TradeFeatures,
    TrainingConfig,
    TrainingResult,
    WalkForwardTrainer,
    WeightConfig,
    WeightedScorer,
    format_training_summary,
)
from .validation import (
    ComponentCorrelation,
    RegimeBucketStats,
    ReliabilityResult,
    ReliabilityScorer,
    ScoreBucketStats,
    ScorerConfig,
    SignalReliability,
    SignalValidationResult,
    SignalValidator,
    StatisticalCalculator,
    create_scorer_from_latest_model,
    format_reliability_badge,
    format_reliability_report,
)

__all__ = [
    # Engine
    "BacktestEngine",
    "BacktestConfig",
    "BacktestResult",
    "TradeResult",
    "TradeOutcome",
    "ExitReason",
    # Metrics
    "PerformanceMetrics",
    "calculate_metrics",
    "calculate_sharpe_ratio",
    "calculate_max_drawdown",
    "calculate_profit_factor",
    # Simulator
    "TradeSimulator",
    "SimulatedTrade",
    "PriceSimulator",
    # Options Simulator (Black-Scholes)
    "OptionsSimulator",
    "SpreadEntry",
    "SpreadSnapshot",
    "OptionsSimulatorConfig",
    "quick_spread_pnl",
    # NumPy batch functions
    "batch_calculate_spread_values",
    "batch_calculate_pnl",
    "batch_check_exit_signals",
    "EXIT_CODE_NAMES",
    # Signal Validation
    "SignalValidator",
    "SignalValidationResult",
    "SignalReliability",
    "ScoreBucketStats",
    "ComponentCorrelation",
    "RegimeBucketStats",
    "StatisticalCalculator",
    "format_reliability_report",
    # Walk-Forward Training
    "WalkForwardTrainer",
    "TrainingConfig",
    "TrainingResult",
    "EpochResult",
    "format_training_summary",
    # Reliability Scoring
    "ReliabilityScorer",
    "ReliabilityResult",
    "ScorerConfig",
    "create_scorer_from_latest_model",
    "format_reliability_badge",
    # Trade Tracker
    "TradeTracker",
    "TrackedTrade",
    "TradeStats",
    "TradeStatus",
    "TrackerOutcome",
    "PriceBar",
    "SymbolPriceData",
    "VixDataPoint",
    "OptionBar",
    "format_trade_stats",
    "create_tracker",
    # Data Collector
    "DataCollector",
    "CollectionConfig",
    "CollectionResult",
    "format_collection_status",
    "run_daily_collection",
    "create_collector",
    # Regime Config
    "RegimeConfig",
    "RegimeType",
    "RegimeBoundaryMethod",
    "RegimeState",
    "RegimeTransition",
    "FIXED_REGIMES",
    "create_percentile_regimes",
    "get_regime_for_vix",
    "save_regimes",
    "load_regimes",
    "format_regime_summary",
    # Trained Model Support
    "TrainedModelLoader",
    "TrainedRegimeConfig",
    "TrainedStrategyConfig",
    "get_trained_model_loader",
    "load_trained_regimes",
    "REGIME_NAME_MAPPING",
    # Regime Training
    "RegimeTrainer",
    "RegimeTrainingConfig",
    "RegimeTrainingResult",
    "FullRegimeTrainingResult",
    "RegimeEpochResult",
    "StrategyPerformance",
    # Regime Model (Production)
    "RegimeModel",
    "TradingParameters",
    "TradeDecision",
    "RegimeStatus",
    "get_regime_recommendation",
    "format_regime_status",
    # ML Weight Optimizer
    "MLWeightOptimizer",
    "OptimizationMethod",
    "OptimizationResult",
    "WeightConfig",
    "ComponentStats",
    "WeightedScorer",
    "STRATEGY_COMPONENTS",
    "ALL_COMPONENTS",
    # Ensemble Strategy Selector
    "EnsembleSelector",
    "MetaLearner",
    "StrategyRotationEngine",
    "StrategyScore",
    "EnsembleRecommendation",
    "SymbolPerformance",
    "RotationState",
    "SelectionMethod",
    "RotationTrigger",
    "create_strategy_score",
    "format_ensemble_summary",
    "STRATEGIES",
    "DEFAULT_REGIME_PREFERENCES",
    # Real Options Backtester (Historical Data)
    "RealOptionsBacktester",
    "OptionsDatabase",
    "SpreadFinder",
    "OutcomeCalculator",
    "OptionQuote",
    "RealSpreadEntry",
    "SpreadOutcome",
    "SpreadOutcomeResult",
    "SetupFeatures",
    "BacktestTradeRecord",
    "quick_backtest",
    "run_symbol_backtest",
    "create_outcome_database",
    "save_outcomes_to_db",
    "load_outcomes_for_training",
    "load_outcomes_dataframe",
    "get_outcome_statistics",
    "train_outcome_predictor",
    "analyze_winning_patterns",
    "calculate_symbol_stability",
    "get_recommended_symbols",
    "get_blacklisted_symbols",
    "get_symbol_stability_score",
    "OUTCOME_DB_PATH",
    # Phase 6: Component Score Training
    "get_trades_without_scores",
    "update_trade_scores",
    "load_outcomes_with_scores",
    "train_component_weights_from_outcomes",
]
