# OptionPlay - Utils Package
# ===========================
# Common utility functions and helpers

from .circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerError,
    CircuitBreakerOpen,
    CircuitBreakerRegistry,
    CircuitState,
    get_circuit_breaker,
    get_circuit_breaker_registry,
    reset_circuit_breakers,
)
from .error_handler import (
    ApiConnectionError,
    ApiTimeoutError,
    ConfigurationError,
    DataFetchError,
    DataParseError,
    ErrorCode,
    InsufficientDataError,
    MCPError,
    NoDataError,
    ProviderError,
    RateLimitError,
    SymbolNotFoundError,
    format_error_response,
    mcp_endpoint,
    safe_format,
    sync_endpoint,
    truncate_string,
)
from .markdown_builder import (
    MarkdownBuilder,
    MarkdownShortcuts,
    TableAlign,
    TableColumn,
    format_date,
    format_percent,
    format_price,
    format_volume,
    md,
    truncate,
)
from .metrics import (
    Counter,
    Gauge,
    Histogram,
    Metric,
    MetricsRegistry,
    active_connections,
    api_latency,
    api_requests,
    cache_hits,
    cache_misses,
    circuit_breaker_state,
    errors,
    metrics,
    rate_limit_waits,
)
from .provider_orchestrator import (
    DataType,
    ProviderConfig,
    ProviderOrchestrator,
    ProviderStats,
    ProviderType,
    format_provider_status,
    get_orchestrator,
)
from .rate_limiter import (
    AdaptiveRateLimiter,
    RateLimitConfig,
    RateLimiter,
    get_limiter,
    get_marketdata_limiter,
    get_tradier_limiter,
    get_yahoo_limiter,
    retry_with_backoff,
)
from .secure_config import (
    SecureConfig,
    get_api_key,
    get_secure_config,
    mask_api_key,
    mask_sensitive_data,
    reset_secure_config,
)
from .structured_logging import (
    StructuredFormatter,
    StructuredLogger,
    configure_logging,
    get_logger,
    log_api_call,
    log_context,
    log_performance,
)
from .validation import (
    ValidationError,
    ValidationLimits,
    is_valid_symbol,
    safe_validate_symbol,
    validate_batch_size,
    validate_delta,
    validate_dte,
    validate_dte_range,
    validate_max_results,
    validate_min_days,
    validate_min_score,
    validate_num_alternatives,
    validate_pause_seconds,
    validate_positive_int,
    validate_right,
    validate_symbol,
    validate_symbols,
)

__all__ = [
    # Rate Limiter
    "RateLimiter",
    "AdaptiveRateLimiter",
    "RateLimitConfig",
    "retry_with_backoff",
    "get_limiter",
    "get_marketdata_limiter",
    "get_tradier_limiter",
    "get_yahoo_limiter",
    # Provider Orchestrator
    "ProviderOrchestrator",
    "ProviderType",
    "DataType",
    "ProviderConfig",
    "ProviderStats",
    "get_orchestrator",
    "format_provider_status",
    # Validation
    "ValidationError",
    "ValidationLimits",
    "validate_symbol",
    "validate_symbols",
    "validate_dte",
    "validate_dte_range",
    "validate_delta",
    "validate_right",
    "validate_positive_int",
    "validate_batch_size",
    "validate_max_results",
    "validate_min_score",
    "validate_num_alternatives",
    "validate_min_days",
    "validate_pause_seconds",
    "safe_validate_symbol",
    "is_valid_symbol",
    # Secure Config
    "SecureConfig",
    "get_secure_config",
    "get_api_key",
    "mask_api_key",
    "mask_sensitive_data",
    "reset_secure_config",
    # Circuit Breaker
    "CircuitBreaker",
    "CircuitBreakerOpen",
    "CircuitBreakerError",
    "CircuitState",
    "CircuitBreakerRegistry",
    "get_circuit_breaker",
    "get_circuit_breaker_registry",
    "reset_circuit_breakers",
    # Error Handler
    "ErrorCode",
    "MCPError",
    "DataFetchError",
    "RateLimitError",
    "ApiTimeoutError",
    "ApiConnectionError",
    "ConfigurationError",
    "ProviderError",
    "SymbolNotFoundError",
    "NoDataError",
    "DataParseError",
    "InsufficientDataError",
    "format_error_response",
    "mcp_endpoint",
    "sync_endpoint",
    "safe_format",
    "truncate_string",
    # Markdown Builder
    "MarkdownBuilder",
    "MarkdownShortcuts",
    "TableAlign",
    "TableColumn",
    "md",
    "format_price",
    "format_percent",
    "format_volume",
    "format_date",
    "truncate",
    # Structured Logging
    "StructuredFormatter",
    "StructuredLogger",
    "get_logger",
    "configure_logging",
    "log_context",
    "log_performance",
    "log_api_call",
    # Metrics
    "Metric",
    "Counter",
    "Gauge",
    "Histogram",
    "MetricsRegistry",
    "metrics",
    "api_requests",
    "api_latency",
    "active_connections",
    "cache_hits",
    "cache_misses",
    "circuit_breaker_state",
    "rate_limit_waits",
    "errors",
]
